import {minify} from 'html-minifier';
import Directory from 'directory-helpers';

const project = new Directory('.');

export default async function() {
  const html = await project.read('src/index.html');
  const minifiedHtml = minify(html, {
    collapseBooleanAttributes: true,
    collapseWhitespace: true,
    decodeEntities: true,
    includeAutoGeneratedTags: false,
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortAttributes: true,
    sortClassName: true,
    useShortDoctype: true
  });
  await project.write({'dist/index.html': minifiedHtml});
}
